package com.supplychain.riskanalysis.dto;

import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Response body returned by POST /analysis/ai-explain.
 * Contains the natural-language narrative generated by Gemini.
 */
@Data
@AllArgsConstructor
public class AiExplainResponse {

    /** Natural-language risk narrative produced by Gemini. */
    private String narrative;
}
