spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:supply_chain}
    username: ${DB_USER:divyanshdhote}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update   # auto-create/update tables on startup
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080